### ISSUE TITLE
Pixel generation type conflicts with CIT Resewn

### ISSUE THREAD

**Issue by shaksternano** [PepperCode1/Item-Model-Fix#10]
Using Pixel generation type, CIT Resewn, and this resourcepack causes the items the resourepack affects to look weird, and large frame drops when many of them are shown on screen, for example when "enchanted" is searched in the creative menu.

https://www.curseforge.com/minecraft/mc-mods/cit-resewn

https://resource-pack.com/enchantment-textures-resource-pack-1-16-3

![2021-10-25_23 07 46](https://user-images.githubusercontent.com/54268387/138777842-f1013a3b-14ad-4471-8024-27805a7e4609.png)

What it should look like:
![2021-10-25_23 09 15](https://user-images.githubusercontent.com/54268387/138777973-1ddedef4-5e7b-4044-8733-2ff5f3fc7b4c.png)

**Comment by SHsuperCM** [comment]
@PepperCode1 
Not related to CIT Resewn.

The pixel generation type drops a lot of frames when the texture is animated and when 
the item is enchanted, the glint is applied multiple times on the same spots causing 
further fps drops.

SHsuperCM/CITResewn#55
> This is not an incompatibility and CIT Resewn is not the reason this is happening. The only way this is related is that CIT Resewn allowed you to load the texture in the pack that had this issue.
> 
> You can recreate this issue without CIT Resewn by copying one of the problematic books out of the pack and using the texture in a vanilla resourcepack(I just replaced all enchanted books with the depth strider one).
> 
> What's happening here is that the enchantment glint is being applied a lot more than it is supposed to when the texture is animated(which is why only the animated books are breaking).
> 
> The pixel generation type creates more boxes than needed on top of eachother which is causing the glint to appear brighter with each pixel that's occupying the same spot as well as contributing to the fps drop.
