### ISSUE TITLE
Mark as working for 1.19 on CurseForge

### ISSUE THREAD

**Issue by helpimnotdrowning** [PepperCode1/Item-Model-Fix#16]
Working perfectly fine on 1.19:\
![image](https://user-images.githubusercontent.com/35247379/172925287-2c6c46f8-f772-41b7-88b2-36f1f2260c24.png)

**Comment by PepperCode1** [comment]
What is the issue? The 1.19 version does indeed work on 1.19.

**Comment by PepperCode1** [comment]
The mod may work, but it will crash as soon as the configuration screen is accessed. I will need to make a proper port soon.

**Comment by PepperCode1** [comment]
The 1.19 version has been uploaded to CurseForge and Modrinth.
