### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by BuckinghamStudios** [PepperCode1/Item-Model-Fix#18]

**Comment by TechPro424** [comment]
+1 Please Update
There's a PR: #17

**Comment by hassanaigehazim** [comment]
Isn't [Continuity](https://modrinth.com/mod/continuity) already updated to 1.19?

**Comment by hassanaigehazim** [comment]
welp, pepper should update that (I accidently wrote in continuity by mistake)

**Comment by kosma** [comment]
In the meantime, grab the code from https://github.com/kosma/Item-Model-Fix and build with `gradlew build`, the resulting mod will be in `build/libs`.

**Comment by PepperCode1** [comment]
The 1.19 version has been uploaded to CurseForge and Modrinth.
