### ISSUE TITLE
Crashed client

### ISSUE THREAD

**Issue by kyrtion** [PepperCode1/Item-Model-Fix#2]
Version mod: new
Minecraft: 1.15.2
Tested and crashed, i can know why crashed - it is modmenu.

**Comment by PepperCode1** [comment]
Could you post the whole log with the crash (in `.minecraft/logs`) into a paste site and then send it here so I can look over it and see what the problem is?

**Comment by kyrtion** [comment]
https://pastebin.com/vGL87etq

**Comment by PepperCode1** [comment]
Thanks. I'll try to fix this in ModMenu itself but if this is not possible then I will release a new version of this mod with the fix instead.

**Comment by PepperCode1** [comment]
The latest version of Mod Menu for 1.15 should not cause a crash with this mod anymore.
