### ISSUE TITLE
Flickering block intersections with many shaders

### ISSUE THREAD

**Issue by Slooshie1** [PepperCode1/Item-Model-Fix#24]
This flickering happens with all shaders I've tested so far aside from AstraLex. Some shaders make it more prominent than others. This happens when only sodium 0.5.1, iris 1.6.7, model fix 1.14, and quilted fabric api 7.1.2 is in the mods folder. I just used Ok Zoomer to zoom into the block corner, which makes the effect more noticeable, but it is still visible with a wide FOV. The shaders used in the clip is Complementary Reimagined, but I have also reproduced the issue with BSL, Solas, and Super Duper Vanilla.

https://github.com/PepperCode1/Item-Model-Fix/assets/90230538/3fa27eea-87e7-4172-b5a1-3bf195902594

**Comment by YukiAyase** [comment]
Are you sure you're reporting an issue with **Item Model Fix**?
The latest version of IMF is for 1.19-1.19.2 and anything >=1.19.3 is non-existent

**Comment by Slooshie1** [comment]
My mistake, I was using a different mod that does the same thing. This is the mod I usually used back in 1.19 so that's why I reported here, assuming I was using this mod. My apologies.
