### ISSUE TITLE
Mod doesn't fix item model

### ISSUE THREAD

**Issue by AliAhmad810** [PepperCode1/Item-Model-Fix#3]
This texture wasn't connecting properly, and I was just wondering how I could fix it. I tried it on all modes, and no method seems to work. If I could get any feedback that be greatly appreciated!

Here is the actual item texture (blown up to 512x, original texture is 16x):
![netherite_sword](https://user-images.githubusercontent.com/57443539/108277385-55246f80-7147-11eb-893d-821169fc4f9b.png)

Here is the texture in game:
![Screen Shot 2021-02-17 at 5 26 11 PM](https://user-images.githubusercontent.com/57443539/108276242-80a65a80-7145-11eb-811a-8879753d210a.png)

Is there any way I can fix this? Thanks!

**Comment by PepperCode1** [comment]
I did some testing, and found out that the pixel between the second and third pixels on the right side is actually not transparent, which makes Minecraft (and this mod) not draw the insides of the other pixels. I have attached the fixed texture.
![item](https://user-images.githubusercontent.com/44146161/108447338-8b7bf080-7214-11eb-8177-d8653c097688.png)
