### ISSUE TITLE
Incompatible with 1.17.

### ISSUE THREAD

**Issue by Kichura** [PepperCode1/Item-Model-Fix#6]
When attempting to use this mod in 1.17, the game just loop-loads since the java code is entirely different.

**Comment by PepperCode1** [comment]
Thank you for the report. I will update this mod to 1.17 by the end of the week.

**Comment by PepperCode1** [comment]
I've published new 1.16 and 1.17 releases to both CurseForge and GitHub, so I'll close this issue.
