### ISSUE TITLE
Single flickering transparent pixels

### ISSUE THREAD

**Issue by d4rkm0nkey** [PepperCode1/Item-Model-Fix#7]
When using this mod the 1 pixel wide gap in items is fixed, but there are still single pixels that flicker between being transparent and not being transparent. This is probably caused by rounding errors.
It's easier to see with Iris and Sildurs Vibrant Shaders and in movement, but it happens without shaders as well.
I guess the epsilon value needs to be increased.

**Comment by PepperCode1** [comment]
Can you provide a screenshot/video and some steps to reproduce this? I'm not quite sure what you're describing.

**Comment by d4rkm0nkey** [comment]
The problem doesn't occur anymore if I set the option in the modmenu config screen to pixel.
I will make a video as soon as possible.

**Comment by d4rkm0nkey** [comment]
https://drive.google.com/file/d/1QicOKj-YLzDqPUi7Fjuyz894fbUFKPVi/view?usp=sharing
I hope that the compression doesn't remove the flickering and that you can see that some pixels are transparent sometimes.
This happens when Outline or Unlerp are selected in the option. Pixel works fine.

**Comment by PepperCode1** [comment]
Oh, are you referencing the single transparent pixels on the edges where the large gaps usually are? That is unavoidable with how unlerp and outline mode work. Pixel mode uses different code which fixes it but causes item rendering to be less efficient. The mode description tooltips essentially say all this in a shortened form. In the end, while this is something that can be improved, it would require hacking around Minecraft's rendering, and even then it may not work, so pixel mode is the current solution.
