### ISSUE TITLE
Strange performance issues with Pixel optimization

### ISSUE THREAD

**Issue by JumperREDACTED** [PepperCode1/Item-Model-Fix#9]
FPS in the top left

It seems like its trying to optimize icons in inventory, its especially apparent with enchanted items.
![2021-10-23_13 02 30](https://user-images.githubusercontent.com/83337894/138554009-dc2d125c-2343-4f18-bee3-8c0b365ba810.png)
![2021-10-23_13 02 47](https://user-images.githubusercontent.com/83337894/138554014-e240bae7-4783-4858-801b-c7a9dc2f612a.jpg)

Same happens with items dropped on the ground
![2021-10-23_13 18 56](https://user-images.githubusercontent.com/83337894/138554042-00f42137-7f5b-4228-8807-51897b816edd.jpg)

again, enchant glint makes it significantly worse

For comparison, here is outline optimisatio
![2021-10-23_13 27 20](https://user-images.githubusercontent.com/83337894/138554114-aadd0683-aa87-4839-83c7-a8a134e84450.png)
n

**Comment by PepperCode1** [comment]
This is expected and cannot be avoided.
